### ISSUE TITLE
Wrong release?

### ISSUE THREAD

**Issue by strongbugman** [p1c2u/openapi-spec-validator#74] opened 2019-05-15 09:36 UTC
The release of [0.2.6](https://github.com/p1c2u/openapi-spec-validator/releases/tag/0.2.6) should include the [commit](https://github.com/p1c2u/openapi-spec-validator/commit/37e38eb0656b42349761f697f05e4d11562a2fb1) which replace "pathlib" with "pathlib2", but the released 0.2.6 does not include this commit, see "setup.py" in the release:
```
......
    install_requires=[
        "jsonschema<3",
        "PyYAML>=3.13",
        "six",
        'pathlib;python_version=="2.7"',
    ],
......
```
Same error with #65

**Comment by p1c2u** [comment] 2019-05-20 09:27
Duplicate of #65  Closing.

**Closed by p1c2u** 2019-05-20 09:27 UTC
Labels: resolution/duplicate
