### ISSUE TITLE
Bad python3.4+ wheel

### ISSUE THREAD

**Issue by cHYzZQo** [p1c2u/openapi-spec-validator#71] opened 2019-03-29 23:48 UTC
The wheels published to pypi for python3 contain bad metadata.

https://files.pythonhosted.org/packages/09/57/d66ecb940d656f6762efa0216317d3b97b7dd0e2b2e07c671c7b1de5a2dc/openapi_spec_validator-0.2.6-py3-none-any.whl

Specifically

```Requires-Dist: pathlib```

Should only be present for python < 3.4.

**Comment by p1c2u** [comment] 2019-05-20 09:27
Duplicate of #65  Closing.

**Closed by p1c2u** 2019-05-20 09:27 UTC
Labels: resolution/duplicate
